apps/account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/machine/urls.py
from django.urls import path
from .views import *

app_name = "machine"
urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  path(
                      "",
                      include("apps.account.urls", namespace="account"),
                  ),
                  path(
                      "machine/",
                      include("apps.machine.urls", namespace="machine"),
                  ),

                  # User management
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

apps/machine/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db import models
from ..account.models import CoinValues
import collections
from django.utils.crypto import get_random_string

user_model = get_user_model()


class MachineMoney(models.Model):
    coin_decimal_value = models.DecimalField(max_digits=6, decimal_places=2)
    coin_value = models.CharField(choices=CoinValues.choices, max_length=6, unique=True)
    quantity = models.IntegerField()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.coin_decimal_value = float(self.coin_value)
        super().save(force_insert, force_update, using, update_fields)

    @property
    def coins_json(self):
        coins_json = {"value": int(self.coin_decimal_value * 100), "count": self.quantity}
        return coins_json


class Product(models.Model):
    name = models.CharField(max_length=150, unique=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name


class SpaceChoices(models.TextChoices):
    AA = 'AA', 'AA'
    AB = 'AB', 'AB'
    AC = 'AC', 'AC'
    BA = 'BA', 'BA'
    BB = 'BB', 'BB'
    BC = 'BC', 'BC'
    CA = 'CA', 'CA'
    CB = 'CB', 'CB'
    CC = 'CC', 'CC'


class Stock(models.Model):
    space = models.CharField(max_length=2, choices=SpaceChoices.choices, unique=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()


class Purchase(models.Model):
    user = models.ForeignKey(user_model, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    history_payment = models.TextField()
    history_change = models.TextField()
    code = models.CharField(max_length=10, blank=True, null=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.code:
            self.code = get_random_string(7)
        super().save(force_insert, force_update, using, update_fields)

apps/machine/forms.py
from django import forms
import warnings
from .models import *
from ..account.models import UserMoney, CoinValues
from django.contrib.auth import authenticate, get_user_model
from .dinamic_coin_change import getchange


class DashboardForm(forms.Form):
    space = forms.ChoiceField(choices=SpaceChoices.choices,
                              widget=forms.Select(attrs={'class': 'form-control'}))
    five_cent = forms.IntegerField(initial=0)
    ten_cent = forms.IntegerField(initial=0)
    twenty_cent = forms.IntegerField(initial=0)
    fifty_cent = forms.IntegerField(initial=0)
    one = forms.IntegerField(initial=0)
    two = forms.IntegerField(initial=0)
    five = forms.IntegerField(initial=0)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(DashboardForm, self).__init__(*args, **kwargs)

    def clean_space(self):
        stock = Stock.objects.get(space=self.cleaned_data.get('space'))
        if stock.quantity <= 0:
            self.add_error('space', 'No hay stock de este producto por favor elija otro.')
        else:
            return self.cleaned_data.get('space')

    def clean_five_cent(self):
        if self.cleaned_data.get('five_cent') < 0:
            self.add_error('five_cent', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('five_cent') > self.validate_stock_user(CoinValues.FIVE_CENT):
            self.add_error('five_cent', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('five_cent')

    def clean_ten_cent(self):
        if self.cleaned_data.get('ten_cent') < 0:
            self.add_error('ten_cent', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('ten_cent') > self.validate_stock_user(CoinValues.TEN_CENT):
            self.add_error('ten_cent', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('ten_cent')

    def clean_twenty_cent(self):
        if self.cleaned_data.get('twenty_cent') < 0:
            self.add_error('twenty_cent', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('twenty_cent') > self.validate_stock_user(CoinValues.TWENTY_CENT):
            self.add_error('twenty_cent', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('twenty_cent')

    def clean_fifty_cent(self):
        if self.cleaned_data.get('fifty_cent') < 0:
            self.add_error('fifty_cent', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('fifty_cent') > self.validate_stock_user(CoinValues.FIFTY_CENT):
            self.add_error('fifty_cent', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('fifty_cent')

    def clean_one(self):
        if self.cleaned_data.get('one') < 0:
            self.add_error('one', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('one') > self.validate_stock_user(CoinValues.ONE):
            self.add_error('one', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('one')

    def clean_two(self):
        if self.cleaned_data.get('two') < 0:
            self.add_error('two', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('two') > self.validate_stock_user(CoinValues.TWO):
            self.add_error('two', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('two')

    def clean_five(self):
        if self.cleaned_data.get('five') < 0:
            self.add_error('five', 'No puede ser menor de 0.')
        elif self.cleaned_data.get('five') > self.validate_stock_user(CoinValues.FIVE):
            self.add_error('five', 'No tienes suficientes monedas tienes que recargar')
        else:
            return self.cleaned_data.get('five')

    def validate_stock_user(self, coin_value):
        user_money = UserMoney.objects.filter(user=self.user, coin_value=coin_value)
        if user_money:
            return user_money.first().quantity
        else:
            return 0

    def clean(self):
        space = self.cleaned_data.get('space')
        five_cent = self.cleaned_data.get('five_cent')
        ten_cent = self.cleaned_data.get('ten_cent')
        twenty_cent = self.cleaned_data.get('twenty_cent')
        fifty_cent = self.cleaned_data.get('fifty_cent')
        one = self.cleaned_data.get('one')
        two = self.cleaned_data.get('two')
        five = self.cleaned_data.get('five')

        if space and five_cent and ten_cent and twenty_cent and fifty_cent and one and two and five:
            stock = Stock.objects.filter(space=space).first()
            total = (five_cent * float(CoinValues.FIVE_CENT)) + (ten_cent * float(CoinValues.TEN_CENT)) + (
                    twenty_cent * float(CoinValues.TWENTY_CENT)) + (fifty_cent * float(CoinValues.FIFTY_CENT)) + (
                            one * float(CoinValues.ONE)) + (two * float(CoinValues.TWO)) + (
                            five * float(CoinValues.FIVE))
            if not stock:
                forms.ValidationError('No hay stock de este producto')
            else:
                if stock.product.price > total:
                    self.add_error('space', 'Dinero Insuficiente por favor agregue mas credito.')
        return self.cleaned_data

apps/machine/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout, get_user_model, login
from django.contrib import auth, messages
from django.views.generic import CreateView, View, UpdateView, ListView, DetailView, TemplateView, FormView
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin, AnonymousRequiredMixin
from class_based_auth_views.views import LoginView
from django.contrib import messages
from .models import *
from .forms import *

from ..account.models import UserMoney


class Dashboard(LoginRequiredMixin, FormView):
    login_url = 'account:login'
    template_name = 'dashboard.html'
    form_class = DashboardForm
    success_url = reverse_lazy('machine:dashboard')

    def get_form_kwargs(self):
        form = super().get_form_kwargs()
        form['user'] = self.request.user
        return form

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['stocks'] = Stock.objects.all()
        context['usercoins'] = UserMoney.objects.filter(user=self.request.user)
        context['user'] = self.request.user
        return context

    def form_valid(self, form):
        total = 0
        message_change = ' '
        message_payment = ' '
        ret = super(Dashboard, self).form_valid(form)
        list_values = [form.cleaned_data.get('five_cent'), form.cleaned_data.get('ten_cent'),
                       form.cleaned_data.get('twenty_cent'), form.cleaned_data.get('fifty_cent'),
                       form.cleaned_data.get('one'), form.cleaned_data.get('two'), form.cleaned_data.get('five')]
        space = form.cleaned_data.get('space')
        for i in range(0, len(list_values)):
            if list_values[i] > 0:
                total += list_values[i] * float(CoinValues.values[i])
        stock = Stock.objects.filter(space=space).first()
        coins = [i.coins_json for i in MachineMoney.objects.all()]
        change = total - float(stock.product.price)
        result = getchange(coins, int(round(change, 2) * 100))
        if result is not None:
            purchase = Purchase.objects.create(user=self.request.user, product=stock.product)
            for i in range(0, len(list_values)):
                if list_values[i] > 0:
                    user = UserMoney.objects.filter(user=self.request.user,
                                                    coin_decimal_value=float(CoinValues.values[i])).first()
                    if not user:
                        UserMoney.objects.create(user=self.request.user,
                                                 coin_value="{:.2f}".format(CoinValues.values[i]),
                                                 quantity=0)
                    user.quantity = user.quantity - list_values[i]
                    user.save()
                    machine = MachineMoney.objects.filter(coin_decimal_value=float(CoinValues.values[i])).first()
                    machine.quantity = machine.quantity + list_values[i]
                    machine.save()
                    message_payment = message_payment + "{} $: {} monedas".format(float(CoinValues.values[i]),
                                                                                  list_values[i])
            purchase.history_payment = "Pago la cantidad de " + message_payment

            for i in result:
                machine = MachineMoney.objects.filter(coin_decimal_value=float(i['value']) / 100).first()
                machine.quantity -= i['count']
                machine.save()
                user = UserMoney.objects.filter(user=self.request.user,
                                                coin_decimal_value=float(i['value']) / 100).first()
                if not user:
                    user = UserMoney.objects.create(user=self.request.user,
                                                    coin_value="{:.2f}".format(i['value'] / 100),
                                                    quantity=0)
                user.quantity += i['count']
                user.save()
                message_change = message_change + "{} $ : {} monedas".format(float(i['value']) / 100, i['count'])
            stock.quantity -= 1
            stock.save()
            if len(message_change) < 2:
                message_change = "0 soles"
            messages.add_message(self.request, messages.SUCCESS, "Su cambio es de " + message_change)
            purchase.history_change = "Su cambio es de " + message_change
            purchase.save()
        else:
            messages.add_message(self.request, messages.SUCCESS, 'La maquina no tiene Cambio')
        return ret

apps/machine/templates/dashboard.html
{% extends "base.html" %}
{% block cuerpo %}
    <div class="section-normal">
        <li><a href="{% url 'account:logout' %}">Salir</a></li>
        <div class="container">
            <div class="col-lg-6 col-lg-offset-3">
                <h1>TIENDA SOFTLAB</h1>
                <div class="col-lg-8 data">
                    <div class="col-lg-12" style="">
                        <p class="">
                            <i class=""></i> {{ user.email }}
                        </p>
                    </div>
                    <div>
                        {% for usercoin in usercoins %}
                            <ul class="">
                                <li>
                                    <i class="">{{ usercoin.coin_value }} ({{ usercoin.quantity }})</i>
                                </li>
                            </ul>
                        {% endfor %}
                    </div>
                    <div>
                        <p> STOCK</p>
                        {% for stock in stocks %}
                            <ul class="">
                                <li>
                                    <i class="">{{ stock.space }} : {{ stock.product.name }}
                                        ({{ stock.quantity }}) [{{ stock.product.price }}]</i>
                                </li>
                            </ul>
                        {% endfor %}
                    </div>
                </div>

                <form action="" method="post" class="form-site col-md-12">
                    {% csrf_token %}
                    <fieldset class="form-group col-md-12">
                        <label for="space">Space </label>
                        {{ form.space }}
                        {% if form.space.errors %}
                            {{ form.space.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="five_cent">5 C </label>
                        {{ form.five_cent }}
                        {% if form.five_cent.errors %}
                            {{ form.five_cent.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="ten_cent">10 C </label>
                        {{ form.ten_cent }}
                        {% if form.ten_cent.errors %}
                            {{ form.ten_cent.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="twenty_cent">20 C </label>
                        {{ form.twenty_cent }}
                        {% if form.twenty_cent.errors %}
                            {{ form.twenty_cent.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="fifty_cent">50 C </label>
                        {{ form.fifty_cent }}
                        {% if form.fifty_cent.errors %}
                            {{ form.fifty_cent.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="one">1 $</label>
                        {{ form.one }}
                        {% if form.one.errors %}
                            {{ form.one.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="two">2 $</label>
                        {{ form.two }}
                        {% if form.two.errors %}
                            {{ form.two.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group col-md-12">
                        <label for="five">5 $</label>
                        {{ form.five }}
                        {% if form.five.errors %}
                            {{ form.five.errors }}
                        {% endif %}
                    </fieldset>
                    <div class="col-md-12">
                        <input type="submit" value="PAGAR" class="btn btn-primary"/>
                    </div>
                </form>

                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock cuerpo %}