apps/account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  path(
                      "",
                      include("apps.account.urls", namespace="account"),
                  ),
                  path(
                      "machine/",
                      include("apps.machine.urls", namespace="machine"),
                  ),

                  # User management
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

apps/account/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db import models

user_model = get_user_model()
# Create your models here.

class CoinValues(models.TextChoices):
    FIVE_CENT = '0.05', 'Cinco Centimos'
    TEN_CENT = '0.10', 'Diez Centimos'
    TWENTY_CENT = '0.20', 'Veinte Centimos'
    FIFTY_CENT = '0.50', 'Cincuenta Centimos'
    ONE = '1.00', 'Un Sol'
    TWO = '2.00', 'Dos Soles'
    FIVE = '5.00', 'Cinco Soles'


class UserMoney(models.Model):
    user = models.ForeignKey(user_model, on_delete=models.PROTECT)
    coin_decimal_value = models.DecimalField(max_digits=6, decimal_places=2)
    coin_value = models.CharField(choices=CoinValues.choices, max_length=6)
    quantity = models.IntegerField()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.coin_decimal_value = float(self.coin_value)
        super().save(force_insert, force_update, using, update_fields)

    class Meta:
        unique_together = (("user", "coin_value"),)

apps/account/forms.py
from django import forms
import warnings
from .models import *
from django.contrib.auth import authenticate, get_user_model


class AuthenticationForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    error_messages = {
        'invalid_login': u'Please enter a correct %(username)s and password.Note that both fields may be case-sensitive.',
        'inactive': u'This account is inactive',
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        UserModel = get_user_model()

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                self.add_error(None,
                               'Por favor, introduzca usuario y password correctos.')
        return self.cleaned_data

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password', 'username')

    def clean_password(self):
        if len(self.cleaned_data.get('password')) < 6:
            self.add_error('password', 'Mínimo 6 caracteres.')
        else:
            return self.cleaned_data.get('password')

    def clean_email(self):  # check if username dos not exist before

        if get_user_model().objects.filter(email=self.cleaned_data['email']).exists():
            self.add_error('email', 'El email ya ha sido registrado.')
        else:
            return self.cleaned_data['email']

    def save(self, commit=True):
        user = get_user_model().objects.create(
            email=self.cleaned_data.get('email'),
            username=self.cleaned_data.get('username'),
        )

        user.set_password(self.cleaned_data.get('password'))
        user.save()
        return user

apps/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout, get_user_model, login
from django.contrib import auth, messages
from django.views.generic import CreateView, View, UpdateView, ListView, DetailView, TemplateView
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin, AnonymousRequiredMixin
from class_based_auth_views.views import LoginView

from .models import *
from .forms import *


class Login(AnonymousRequiredMixin, LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    authenticated_redirect_url = reverse_lazy('machine:dashboard')

    def get_success_url(self):
        return reverse_lazy('machine:dashboard')


class Register(AnonymousRequiredMixin, CreateView):
    model = get_user_model()
    form_class = CreateUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('machine:dashboard')

    def form_valid(self, form):
        self.object = form.save()
        self.object.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, self.object)
        return super(ModelFormMixin, self).form_valid(form)


class LogoutView(View):
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            auth.logout(self.request)
        return redirect(reverse_lazy('account:login'))

apps/account/templates/login.html
{% extends "base.html" %}
{% block cuerpo %}
    <div class="container">
        <div class="row">
            <div class="container">
                <h2>Ingresa</h2>
            </div>
            <div class="row">
                <div class="col s6 z-depth-5">
                    <form action="" method="post" class="form-site col-lg-12">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="input-field">
                            <label>Nombre de Usuario</label>
                            <input autofocus="autofocus" class="form-control" id="user_username"
                                   name="{{ form.username.name }}"
                                   size="30"
                                   type="text">
                            {% if form.username.errors %}
                                {{ form.username.errors }}
                            {% endif %}
                        </div>
                        <div class="input-field">
                            <label>Contraseña</label>
                            <input autofocus="autofocus" class="form-control" id="user_password"
                                   name="{{ form.password.name }}" size="30"
                                   type="password">
                            {% if form.password.errors %}
                                {{ form.password.errors }}
                            {% endif %}
                        </div>
                        <p>
                            <a href="" class="link">¿Olvidaste tu contraseña?</a><br>
                        </p>
                        <div>
                            <button class="btn btn btn-primary" type="submit" name="action">
                                Ingresar
                            </button>
                            <a class="btn btn-warning" href="{% url 'account:register' %}" role="button">Registrate</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock cuerpo %}

apps/account/templates/register.html
{% extends 'base.html' %}
{% block cuerpo %}
    <div class="section-normal">
        <div class="container">
            <div class="col-lg-6 col-lg-offset-3">
                <h1>Registrarse</h1>
                <form action="" method="post" class="form-site col-lg-12">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <label for="user_username">Username</label>
                        <input autofocus="autofocus" class="form-control" id="user_username" name="username"
                               size="30"
                               type="text">
                        {% if form.username.errors %}
                            {{ form.username.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="user_email">Email (*)</label>
                        <input autofocus="autofocus" class="form-control" id="user_email" name="email" size="30"
                               type="email">
                        {% if form.email.errors %}
                            {{ form.email.errors }}
                        {% endif %}
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="user_password">Contraseña (*)</label>
                        <input autofocus="autofocus" class="form-control" id="user_password" name="password" size="30"
                               type="password">
                        {% if form.password.errors %}
                            {{ form.password.errors }}
                        {% endif %}
                    </fieldset>
                    <div>
                        <input type="submit" value="Registrarse" class="btn btn btn-primary"/>
                        <a class="btn btn-danger" href="{% url 'account:login' %}" role="button">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}